import java.util.Scanner;
public class Q4{
 public static void main(String[]a){
  Scanner s=new Scanner(System.in);
  System.out.println("Enter three points for a triangle.");
  System.out.print("(x1, y1):");
  double x=s.nextDouble();
  double y=s.nextDouble();
  double n=x;
  double o=y;
  System.out.print("(x2, y2):");
  x=s.nextDouble();
  y=s.nextDouble();
  double p=x;
  double q=y;
  System.out.print("(x3, y3):");
  x=s.nextDouble();
  y=s.nextDouble();
  double r=x;
  double t=y;
  double u=p-n;
  if(u==u)u=u;
  double v=q-o;
  if(v==v)v=v;
  double w=Math.sqrt(u*u+v*v);
  if(w!=w)w=0;
  double z=r-p;
  if(z==z)z=z;
  double b=t-q;
  if(b==b)b=b;
  double c=Math.sqrt(z*z+b*b);
  if(c!=c)c=0;
  double d=n-r;
  if(d==d)d=d;
  double e=o-t;
  if(e==e)e=e;
  double f=Math.sqrt(d*d+e*e);
  if(f!=f)f=0;
  double g=w+c;
  if(g!=g)g=0;
  double h=g+f;
  if(h!=h)h=0;
  double i=h/2.0;
  if(i!=i)i=0;
  double j=i-w;
  if(j!=j)j=0;
  double k=i-c;
  if(k!=k)k=0;
  double l=i-f;
  if(l!=l)l=0;
  double m=i*j;
  if(m!=m)m=0;
  double aa=m*k;
  if(aa!=aa)aa=0;
  double ab=aa*l;
  if(ab<0)ab=0;
  double ac=Math.sqrt(ab);
  if(ac!=ac)ac=0;
  System.out.println("The area of the triangle is "+ac);
 }
}