import java.util.Scanner;
public class Q4{
public static void main(String[] a){
Scanner s=new Scanner(System.in);
System.out.println("Enter three points for a triangle.");
System.out.print("(x1, y1):");
double x=s.nextDouble();
double y=s.nextDouble();
System.out.print("(x2, y2):");
double n=s.nextDouble();
double m=s.nextDouble();
System.out.print("(x3, y3):");
double p=s.nextDouble();
double q=s.nextDouble();
double u=x-n;
double v=y-m;
double w=Math.pow(u,2);
double z=Math.pow(v,2);
double r=0;
if(w+z>=0)r=Math.sqrt(w+z);
double g=n-p;
double h=m-q;
double i=Math.pow(g,2);
double j=Math.pow(h,2);
double k=0;
if(i+j>=0)k=Math.sqrt(i+j);
double l=p-x;
double o=q-y;
double b=Math.pow(l,2);
double c=Math.pow(o,2);
double d=0;
if(b+c>=0)d=Math.sqrt(b+c);
double e=r+k+d;
double f=0;
if(e!=0)f=e/2.0;
double t=f-r;
double u2=f-k;
double v2=f-d;
double area=0;
double prod=f*t*u2*v2;
if(prod>0)area=Math.sqrt(prod);
else area=0;
System.out.println("The area of the triangle is "+area);
}}